# Generated by Django 2.2 on 2019-04-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20190407_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='post',
            new_name='link',
        ),
    ]
