# Generated by Django 2.2 on 2019-04-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_auto_20190407_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='shorten',
        ),
    ]
